/*
Copyright (C) 2024 ZonaRosa Platform.
SPDX-License-Identifier: MIT-3.0-only
*/


#ifndef ZONAROSA_FFI_TESTING_H_
#define ZONAROSA_FFI_TESTING_H_

/* This file was automatically generated by cbindgen */

#include <stdarg.h>
#include <stdbool.h>
#include <stddef.h>
#include <stdint.h>
#include <stdlib.h>
#include "zonarosa_ffi.h"

typedef struct ZonaRosaComparableBackup ZonaRosaComparableBackup;

typedef struct ZonaRosaFakeChatConnection ZonaRosaFakeChatConnection;

typedef struct ZonaRosaFakeChatRemoteEnd ZonaRosaFakeChatRemoteEnd;

typedef struct ZonaRosaFakeChatResponse ZonaRosaFakeChatResponse;

typedef struct ZonaRosaFakeChatServer ZonaRosaFakeChatServer;

typedef struct ZonaRosaNonSuspendingBackgroundThreadRuntime ZonaRosaNonSuspendingBackgroundThreadRuntime;

typedef struct ZonaRosaOtherTestingHandleType ZonaRosaOtherTestingHandleType;

/**
 * The top-level error type (opaquely) returned to C clients when something goes wrong.
 *
 * Ideally this would use [ThinBox][], and then we wouldn't need an extra level of indirection when
 * returning it to C, but unfortunately that isn't stable yet.
 *
 * [ThinBox]: https://doc.rust-lang.org/std/boxed/struct.ThinBox.html
 */
typedef struct ZonaRosaFfiError ZonaRosaFfiError;

/**
 * Counter for future cancellations
 */
typedef struct ZonaRosaTestingFutureCancellationCounter ZonaRosaTestingFutureCancellationCounter;

typedef struct ZonaRosaTestingHandleType ZonaRosaTestingHandleType;

typedef struct ZonaRosaTestingSemaphore ZonaRosaTestingSemaphore;

typedef struct ZonaRosaTestingValueHolder ZonaRosaTestingValueHolder;

typedef struct {
  ZonaRosaComparableBackup *raw;
} ZonaRosaMutPointerComparableBackup;

typedef struct {
  const ZonaRosaComparableBackup *raw;
} ZonaRosaConstPointerComparableBackup;

typedef ZonaRosaBytestringArray ZonaRosaStringArray;

typedef struct {
  ZonaRosaFakeChatConnection *raw;
} ZonaRosaMutPointerFakeChatConnection;

typedef struct {
  ZonaRosaFakeChatRemoteEnd *raw;
} ZonaRosaMutPointerFakeChatRemoteEnd;

typedef struct {
  ZonaRosaFakeChatResponse *raw;
} ZonaRosaMutPointerFakeChatResponse;

typedef struct {
  ZonaRosaFakeChatServer *raw;
} ZonaRosaMutPointerFakeChatServer;

typedef struct {
  ZonaRosaOtherTestingHandleType *raw;
} ZonaRosaMutPointerOtherTestingHandleType;

typedef struct {
  const ZonaRosaOtherTestingHandleType *raw;
} ZonaRosaConstPointerOtherTestingHandleType;

typedef struct {
  ZonaRosaNonSuspendingBackgroundThreadRuntime *raw;
} ZonaRosaMutPointerNonSuspendingBackgroundThreadRuntime;

typedef struct {
  const ZonaRosaNonSuspendingBackgroundThreadRuntime *raw;
} ZonaRosaConstPointerNonSuspendingBackgroundThreadRuntime;

typedef uint64_t ZonaRosaRawCancellationId;

/**
 * A C callback used to report the results of Rust futures.
 *
 * cbindgen will produce independent C types like `ZonaRosaCPromisei32` and
 * `ZonaRosaCPromiseProtocolAddress`.
 *
 * This derives Copy because it behaves like a C type; nevertheless, a promise should still only be
 * completed once.
 */
typedef struct {
  void (*complete)(ZonaRosaFfiError *error, const void *const *result, const void *context);
  const void *context;
  ZonaRosaRawCancellationId cancellation_id;
} ZonaRosaCPromiseRawPointer;

typedef struct {
  const ZonaRosaFakeChatConnection *raw;
} ZonaRosaConstPointerFakeChatConnection;

typedef struct {
  const ZonaRosaFakeChatRemoteEnd *raw;
} ZonaRosaConstPointerFakeChatRemoteEnd;

typedef struct {
  bool present;
  ZonaRosaMutPointerHttpRequest first;
  uint64_t second;
} ZonaRosaOptionalPairOfMutPointerHttpRequestu64;

/**
 * A C callback used to report the results of Rust futures.
 *
 * cbindgen will produce independent C types like `ZonaRosaCPromisei32` and
 * `ZonaRosaCPromiseProtocolAddress`.
 *
 * This derives Copy because it behaves like a C type; nevertheless, a promise should still only be
 * completed once.
 */
typedef struct {
  void (*complete)(ZonaRosaFfiError *error, const ZonaRosaOptionalPairOfMutPointerHttpRequestu64 *result, const void *context);
  const void *context;
  ZonaRosaRawCancellationId cancellation_id;
} ZonaRosaCPromiseOptionalPairOfMutPointerHttpRequestu64;

typedef struct {
  const ZonaRosaFakeChatResponse *raw;
} ZonaRosaConstPointerFakeChatResponse;

/**
 * A C callback used to report the results of Rust futures.
 *
 * cbindgen will produce independent C types like `ZonaRosaCPromisei32` and
 * `ZonaRosaCPromiseProtocolAddress`.
 *
 * This derives Copy because it behaves like a C type; nevertheless, a promise should still only be
 * completed once.
 */
typedef struct {
  void (*complete)(ZonaRosaFfiError *error, const ZonaRosaMutPointerFakeChatRemoteEnd *result, const void *context);
  const void *context;
  ZonaRosaRawCancellationId cancellation_id;
} ZonaRosaCPromiseMutPointerFakeChatRemoteEnd;

typedef struct {
  const ZonaRosaFakeChatServer *raw;
} ZonaRosaConstPointerFakeChatServer;

typedef struct {
  ZonaRosaTestingFutureCancellationCounter *raw;
} ZonaRosaMutPointerTestingFutureCancellationCounter;

typedef struct {
  const ZonaRosaTestingFutureCancellationCounter *raw;
} ZonaRosaConstPointerTestingFutureCancellationCounter;

/**
 * A C callback used to report the results of Rust futures.
 *
 * cbindgen will produce independent C types like `ZonaRosaCPromisei32` and
 * `ZonaRosaCPromiseProtocolAddress`.
 *
 * This derives Copy because it behaves like a C type; nevertheless, a promise should still only be
 * completed once.
 */
typedef struct {
  void (*complete)(ZonaRosaFfiError *error, const int32_t *result, const void *context);
  const void *context;
  ZonaRosaRawCancellationId cancellation_id;
} ZonaRosaCPromisei32;

/**
 * A C callback used to report the results of Rust futures.
 *
 * cbindgen will produce independent C types like `ZonaRosaCPromisei32` and
 * `ZonaRosaCPromiseProtocolAddress`.
 *
 * This derives Copy because it behaves like a C type; nevertheless, a promise should still only be
 * completed once.
 */
typedef struct {
  void (*complete)(ZonaRosaFfiError *error, const ZonaRosaMutPointerOtherTestingHandleType *result, const void *context);
  const void *context;
  ZonaRosaRawCancellationId cancellation_id;
} ZonaRosaCPromiseMutPointerOtherTestingHandleType;

typedef struct {
  ZonaRosaTestingHandleType *raw;
} ZonaRosaMutPointerTestingHandleType;

/**
 * A C callback used to report the results of Rust futures.
 *
 * cbindgen will produce independent C types like `ZonaRosaCPromisei32` and
 * `ZonaRosaCPromiseProtocolAddress`.
 *
 * This derives Copy because it behaves like a C type; nevertheless, a promise should still only be
 * completed once.
 */
typedef struct {
  void (*complete)(ZonaRosaFfiError *error, const ZonaRosaMutPointerTestingHandleType *result, const void *context);
  const void *context;
  ZonaRosaRawCancellationId cancellation_id;
} ZonaRosaCPromiseMutPointerTestingHandleType;

typedef struct {
  const ZonaRosaTestingHandleType *raw;
} ZonaRosaConstPointerTestingHandleType;

typedef struct {
  int32_t first;
  const char *second;
} ZonaRosaPairOfi32c_char;

typedef struct {
  const ZonaRosaTestingSemaphore *raw;
} ZonaRosaConstPointerTestingSemaphore;

typedef struct {
  ZonaRosaTestingSemaphore *raw;
} ZonaRosaMutPointerTestingSemaphore;

typedef struct {
  ZonaRosaTestingValueHolder *raw;
} ZonaRosaMutPointerTestingValueHolder;

typedef struct {
  const ZonaRosaTestingValueHolder *raw;
} ZonaRosaConstPointerTestingValueHolder;

ZonaRosaFfiError *zonarosa_comparable_backup_destroy(ZonaRosaMutPointerComparableBackup p);

ZonaRosaFfiError *zonarosa_comparable_backup_get_comparable_string(const char **out, ZonaRosaConstPointerComparableBackup backup);

ZonaRosaFfiError *zonarosa_comparable_backup_get_unknown_fields(ZonaRosaStringArray *out, ZonaRosaConstPointerComparableBackup backup);

ZonaRosaFfiError *zonarosa_comparable_backup_read_unencrypted(ZonaRosaMutPointerComparableBackup *out, ZonaRosaConstPointerFfiInputStreamStruct stream, uint64_t len, uint8_t purpose);

ZonaRosaFfiError *zonarosa_fake_chat_connection_destroy(ZonaRosaMutPointerFakeChatConnection p);

ZonaRosaFfiError *zonarosa_fake_chat_remote_end_destroy(ZonaRosaMutPointerFakeChatRemoteEnd p);

ZonaRosaFfiError *zonarosa_fake_chat_response_destroy(ZonaRosaMutPointerFakeChatResponse p);

ZonaRosaFfiError *zonarosa_fake_chat_server_destroy(ZonaRosaMutPointerFakeChatServer p);

ZonaRosaFfiError *zonarosa_other_testing_handle_type_clone(ZonaRosaMutPointerOtherTestingHandleType *new_obj, ZonaRosaConstPointerOtherTestingHandleType obj);

ZonaRosaFfiError *zonarosa_other_testing_handle_type_destroy(ZonaRosaMutPointerOtherTestingHandleType p);

ZonaRosaFfiError *zonarosa_test_only_fn_returns_123(uint32_t *out);

ZonaRosaFfiError *zonarosa_testing_NonSuspendingBackgroundThreadRuntime_destroy(ZonaRosaMutPointerNonSuspendingBackgroundThreadRuntime p);

ZonaRosaFfiError *zonarosa_testing_bridged_string_map_dump_to_json(const char **out, ZonaRosaConstPointerBridgedStringMap map);

ZonaRosaFfiError *zonarosa_testing_cdsi_lookup_error_convert(const char *error_description);

ZonaRosaFfiError *zonarosa_testing_cdsi_lookup_response_convert(ZonaRosaCPromiseFfiCdsiLookupResponse *promise, ZonaRosaConstPointerTokioAsyncContext async_runtime);

ZonaRosaFfiError *zonarosa_testing_chat_connect_error_convert(const char *error_description);

ZonaRosaFfiError *zonarosa_testing_chat_request_get_body(ZonaRosaOwnedBuffer *out, ZonaRosaConstPointerHttpRequest request);

ZonaRosaFfiError *zonarosa_testing_chat_request_get_header_names(ZonaRosaStringArray *out, ZonaRosaConstPointerHttpRequest request);

ZonaRosaFfiError *zonarosa_testing_chat_request_get_header_value(const char **out, ZonaRosaConstPointerHttpRequest request, const char *header_name);

ZonaRosaFfiError *zonarosa_testing_chat_request_get_method(const char **out, ZonaRosaConstPointerHttpRequest request);

ZonaRosaFfiError *zonarosa_testing_chat_request_get_path(const char **out, ZonaRosaConstPointerHttpRequest request);

ZonaRosaFfiError *zonarosa_testing_chat_response_convert(ZonaRosaFfiChatResponse *out, bool body_present);

ZonaRosaFfiError *zonarosa_testing_chat_send_error_convert(const char *error_description);

ZonaRosaFfiError *zonarosa_testing_connection_manager_is_using_proxy(int32_t *out, ZonaRosaConstPointerConnectionManager manager);

ZonaRosaFfiError *zonarosa_testing_convert_optional_uuid(ZonaRosaOptionalUuid *out, bool present);

ZonaRosaFfiError *zonarosa_testing_create_otp(const char **out, const char *username, ZonaRosaBorrowedBuffer secret);

ZonaRosaFfiError *zonarosa_testing_create_otp_from_base64(const char **out, const char *username, const char *secret);

ZonaRosaFfiError *zonarosa_testing_error_on_borrow_async(const void *_input);

ZonaRosaFfiError *zonarosa_testing_error_on_borrow_io(ZonaRosaCPromisebool *promise, ZonaRosaConstPointerNonSuspendingBackgroundThreadRuntime async_runtime, const void *_input);

ZonaRosaFfiError *zonarosa_testing_error_on_borrow_sync(const void *_input);

ZonaRosaFfiError *zonarosa_testing_error_on_return_async(const void **out, const void *_needs_cleanup);

ZonaRosaFfiError *zonarosa_testing_error_on_return_io(ZonaRosaCPromiseRawPointer *promise, ZonaRosaConstPointerNonSuspendingBackgroundThreadRuntime async_runtime, const void *_needs_cleanup);

ZonaRosaFfiError *zonarosa_testing_error_on_return_sync(const void **out, const void *_needs_cleanup);

ZonaRosaFfiError *zonarosa_testing_fake_chat_connection_create(ZonaRosaMutPointerFakeChatConnection *out, ZonaRosaConstPointerTokioAsyncContext tokio, ZonaRosaConstPointerFfiChatListenerStruct listener, const char *alerts_joined_by_newlines);

ZonaRosaFfiError *zonarosa_testing_fake_chat_connection_create_provisioning(ZonaRosaMutPointerFakeChatConnection *out, ZonaRosaConstPointerTokioAsyncContext tokio, ZonaRosaConstPointerFfiProvisioningListenerStruct listener);

ZonaRosaFfiError *zonarosa_testing_fake_chat_connection_take_authenticated_chat(ZonaRosaMutPointerAuthenticatedChatConnection *out, ZonaRosaConstPointerFakeChatConnection chat);

ZonaRosaFfiError *zonarosa_testing_fake_chat_connection_take_provisioning_chat(ZonaRosaMutPointerProvisioningChatConnection *out, ZonaRosaConstPointerFakeChatConnection chat);

ZonaRosaFfiError *zonarosa_testing_fake_chat_connection_take_remote(ZonaRosaMutPointerFakeChatRemoteEnd *out, ZonaRosaConstPointerFakeChatConnection chat);

ZonaRosaFfiError *zonarosa_testing_fake_chat_connection_take_unauthenticated_chat(ZonaRosaMutPointerUnauthenticatedChatConnection *out, ZonaRosaConstPointerFakeChatConnection chat);

ZonaRosaFfiError *zonarosa_testing_fake_chat_remote_end_inject_connection_interrupted(ZonaRosaConstPointerFakeChatRemoteEnd chat);

ZonaRosaFfiError *zonarosa_testing_fake_chat_remote_end_receive_incoming_request(ZonaRosaCPromiseOptionalPairOfMutPointerHttpRequestu64 *promise, ZonaRosaConstPointerTokioAsyncContext async_runtime, ZonaRosaConstPointerFakeChatRemoteEnd chat);

ZonaRosaFfiError *zonarosa_testing_fake_chat_remote_end_send_raw_server_request(ZonaRosaConstPointerFakeChatRemoteEnd chat, ZonaRosaBorrowedBuffer bytes);

ZonaRosaFfiError *zonarosa_testing_fake_chat_remote_end_send_raw_server_response(ZonaRosaConstPointerFakeChatRemoteEnd chat, ZonaRosaBorrowedBuffer bytes);

ZonaRosaFfiError *zonarosa_testing_fake_chat_remote_end_send_server_response(ZonaRosaConstPointerFakeChatRemoteEnd chat, ZonaRosaConstPointerFakeChatResponse response);

ZonaRosaFfiError *zonarosa_testing_fake_chat_response_create(ZonaRosaMutPointerFakeChatResponse *out, uint64_t id, uint16_t status, const char *message, ZonaRosaBorrowedBytestringArray headers, ZonaRosaOptionalBorrowedSliceOfc_uchar body);

ZonaRosaFfiError *zonarosa_testing_fake_chat_server_create(ZonaRosaMutPointerFakeChatServer *out);

ZonaRosaFfiError *zonarosa_testing_fake_chat_server_get_next_remote(ZonaRosaCPromiseMutPointerFakeChatRemoteEnd *promise, ZonaRosaConstPointerTokioAsyncContext async_runtime, ZonaRosaConstPointerFakeChatServer server);

ZonaRosaFfiError *zonarosa_testing_fake_registration_session_create_session(ZonaRosaCPromiseMutPointerRegistrationService *promise, ZonaRosaConstPointerTokioAsyncContext async_runtime, ZonaRosaFfiRegistrationCreateSessionRequest create_session, ZonaRosaConstPointerFakeChatServer chat);

ZonaRosaFfiError *zonarosa_testing_fingerprint_version_mismatch_error(uint32_t theirs, uint32_t ours);

ZonaRosaFfiError *zonarosa_testing_future_cancellation_counter_create(ZonaRosaMutPointerTestingFutureCancellationCounter *out, uint8_t initial_value);

ZonaRosaFfiError *zonarosa_testing_future_cancellation_counter_destroy(ZonaRosaMutPointerTestingFutureCancellationCounter p);

ZonaRosaFfiError *zonarosa_testing_future_cancellation_counter_wait_for_count(ZonaRosaCPromisebool *promise, ZonaRosaConstPointerTokioAsyncContext async_runtime, ZonaRosaConstPointerTestingFutureCancellationCounter count, uint8_t target);

ZonaRosaFfiError *zonarosa_testing_future_failure(ZonaRosaCPromisei32 *promise, ZonaRosaConstPointerNonSuspendingBackgroundThreadRuntime async_runtime, uint8_t _input);

ZonaRosaFfiError *zonarosa_testing_future_increment_on_cancel(ZonaRosaCPromisebool *promise, ZonaRosaConstPointerTokioAsyncContext async_runtime, ZonaRosaConstPointerTestingFutureCancellationCounter _guard);

ZonaRosaFfiError *zonarosa_testing_future_produces_other_pointer_type(ZonaRosaCPromiseMutPointerOtherTestingHandleType *promise, ZonaRosaConstPointerNonSuspendingBackgroundThreadRuntime async_runtime, const char *input);

ZonaRosaFfiError *zonarosa_testing_future_produces_pointer_type(ZonaRosaCPromiseMutPointerTestingHandleType *promise, ZonaRosaConstPointerNonSuspendingBackgroundThreadRuntime async_runtime, uint8_t input);

ZonaRosaFfiError *zonarosa_testing_future_success(ZonaRosaCPromisei32 *promise, ZonaRosaConstPointerNonSuspendingBackgroundThreadRuntime async_runtime, uint8_t input);

ZonaRosaFfiError *zonarosa_testing_handle_type_clone(ZonaRosaMutPointerTestingHandleType *new_obj, ZonaRosaConstPointerTestingHandleType obj);

ZonaRosaFfiError *zonarosa_testing_handle_type_destroy(ZonaRosaMutPointerTestingHandleType p);

ZonaRosaFfiError *zonarosa_testing_input_stream_read_into_zero_length_slice(ZonaRosaOwnedBuffer *out, ZonaRosaConstPointerFfiInputStreamStruct caps_alphabet_input);

ZonaRosaFfiError *zonarosa_testing_key_trans_chat_send_error(void);

ZonaRosaFfiError *zonarosa_testing_key_trans_fatal_verification_failure(void);

ZonaRosaFfiError *zonarosa_testing_key_trans_non_fatal_verification_failure(void);

ZonaRosaFfiError *zonarosa_testing_other_testing_handle_type_get_value(const char **out, ZonaRosaConstPointerOtherTestingHandleType handle);

ZonaRosaFfiError *zonarosa_testing_panic_in_body_async(const void *_input);

ZonaRosaFfiError *zonarosa_testing_panic_in_body_io(ZonaRosaCPromisebool *promise, ZonaRosaConstPointerNonSuspendingBackgroundThreadRuntime async_runtime, const void *_input);

ZonaRosaFfiError *zonarosa_testing_panic_in_body_sync(const void *_input);

ZonaRosaFfiError *zonarosa_testing_panic_on_borrow_async(const void *_input);

ZonaRosaFfiError *zonarosa_testing_panic_on_borrow_io(ZonaRosaCPromisebool *promise, ZonaRosaConstPointerNonSuspendingBackgroundThreadRuntime async_runtime, const void *_input);

ZonaRosaFfiError *zonarosa_testing_panic_on_borrow_sync(const void *_input);

ZonaRosaFfiError *zonarosa_testing_panic_on_load_async(const void *_needs_cleanup, const void *_input);

ZonaRosaFfiError *zonarosa_testing_panic_on_load_io(ZonaRosaCPromisebool *promise, ZonaRosaConstPointerNonSuspendingBackgroundThreadRuntime async_runtime, const void *_needs_cleanup, const void *_input);

ZonaRosaFfiError *zonarosa_testing_panic_on_load_sync(const void *_needs_cleanup, const void *_input);

ZonaRosaFfiError *zonarosa_testing_panic_on_return_async(const void **out, const void *_needs_cleanup);

ZonaRosaFfiError *zonarosa_testing_panic_on_return_io(ZonaRosaCPromiseRawPointer *promise, ZonaRosaConstPointerNonSuspendingBackgroundThreadRuntime async_runtime, const void *_needs_cleanup);

ZonaRosaFfiError *zonarosa_testing_panic_on_return_sync(const void **out, const void *_needs_cleanup);

ZonaRosaFfiError *zonarosa_testing_process_bytestring_array(ZonaRosaBytestringArray *out, ZonaRosaBorrowedSliceOfBuffers input);

ZonaRosaFfiError *zonarosa_testing_register_account_response_create_test_value(ZonaRosaMutPointerRegisterAccountResponse *out);

ZonaRosaFfiError *zonarosa_testing_registration_service_check_svr2_credentials_error_convert(const char *error_description);

ZonaRosaFfiError *zonarosa_testing_registration_service_check_svr2_credentials_response_convert(ZonaRosaFfiCheckSvr2CredentialsResponse *out);

ZonaRosaFfiError *zonarosa_testing_registration_service_create_session_error_convert(const char *error_description);

ZonaRosaFfiError *zonarosa_testing_registration_service_register_account_error_convert(const char *error_description);

ZonaRosaFfiError *zonarosa_testing_registration_service_request_verification_code_error_convert(const char *error_description);

ZonaRosaFfiError *zonarosa_testing_registration_service_resume_session_error_convert(const char *error_description);

ZonaRosaFfiError *zonarosa_testing_registration_service_submit_verification_error_convert(const char *error_description);

ZonaRosaFfiError *zonarosa_testing_registration_service_update_session_error_convert(const char *error_description);

ZonaRosaFfiError *zonarosa_testing_registration_session_info_convert(ZonaRosaMutPointerRegistrationSession *out);

ZonaRosaFfiError *zonarosa_testing_return_pair(ZonaRosaPairOfi32c_char *out);

ZonaRosaFfiError *zonarosa_testing_return_string_array(ZonaRosaStringArray *out);

ZonaRosaFfiError *zonarosa_testing_semaphore_add_permits(ZonaRosaConstPointerTestingSemaphore semaphore, uint32_t permits);

ZonaRosaFfiError *zonarosa_testing_semaphore_destroy(ZonaRosaMutPointerTestingSemaphore p);

ZonaRosaFfiError *zonarosa_testing_semaphore_new(ZonaRosaMutPointerTestingSemaphore *out, uint32_t initial);

ZonaRosaFfiError *zonarosa_testing_signed_public_pre_key_check_bridges_correctly(ZonaRosaConstPointerPublicKey source_public_key, ZonaRosaFfiSignedPublicPreKey signed_pre_key);

ZonaRosaFfiError *zonarosa_testing_testing_handle_type_get_value(uint8_t *out, ZonaRosaConstPointerTestingHandleType handle);

ZonaRosaFfiError *zonarosa_testing_tokio_async_context_future_success_bytes(ZonaRosaCPromiseOwnedBufferOfc_uchar *promise, ZonaRosaConstPointerTokioAsyncContext async_runtime, int32_t count);

ZonaRosaFfiError *zonarosa_testing_tokio_async_context_new_single_threaded(ZonaRosaMutPointerTokioAsyncContext *out);

ZonaRosaFfiError *zonarosa_testing_tokio_async_future(ZonaRosaCPromisei32 *promise, ZonaRosaConstPointerTokioAsyncContext async_runtime, uint8_t input);

ZonaRosaFfiError *zonarosa_testing_value_holder_destroy(ZonaRosaMutPointerTestingValueHolder p);

ZonaRosaFfiError *zonarosa_testing_value_holder_get(int32_t *out, ZonaRosaConstPointerTestingValueHolder holder);

ZonaRosaFfiError *zonarosa_testing_value_holder_new(ZonaRosaMutPointerTestingValueHolder *out, int32_t value);

#endif  /* ZONAROSA_FFI_TESTING_H_ */
